### ISSUE TITLE
HideSection uses various 1.35 deprecated methods

### ISSUE THREAD

**Issue by RhinosF1** [labster/HideSection#1]
> ErrorException: Use of ParserSectionCreate hook (used in HideSectionHooks::onParserSectionCreate) was deprecated in MediaWiki 1.35. [Called from MediaWiki\HookContainer\HookContainer::run]

and
> ErrorException: Use of SkinTemplateOutputPageBeforeExec hook (used in HideSectionHooks::onSkinTemplateOutputPageBeforeExec) was deprecated in MediaWiki 1.35. [Called from MediaWiki\HookContainer\HookContainer::run]

See https://phabricator.miraheze.org/T7117

**Comment by labster** [comment]
Unfortunately, they deprecated the feature before implementing its replacement.  If you look at https://www.mediawiki.org/wiki/Manual:Hooks/ParserSectionCreate you can see that the hook has no replacement, and we are supposed to get `<section>` tags around sections of each article under headers.  Skin:Minerva implements this, but Skin:Vector does not.  So right now the only way to replicate this functionality is to reparse the wikitext entirely, or throw a mess of Javascript at it, or to redirect all users to the mobile site.

It would be nice if the new functionality was actually implemented before the deprecation occurred.

**Comment by RhinosF1** [comment]
I guess that makes it not a 1.36 blocker for us and for later ™️

**Comment by labster** [comment]
I created a new version that doesn't use this hook at all in branch `removehook`.  I've tested it locally and it seems to be working good.  For @miraheze workflow, how do y'all like handling versioning in extensions?  Should I create tags or something to use?

**Comment by labster** [comment]
Fixed in 6e2c6ce.  You can pull master now.  I've added a v2 tag for fun now as well.
